### ISSUE TITLE
Enable Changing of "rack_allocation" Block

### ISSUE THREAD

**Issue by ProfMoo** [instaclustr/terraform-provider-instaclustr#36]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It'd be great if we could alter this block in Terraform
```
rack_allocation = {
    number_of_racks = var.number_of_racks
    nodes_per_rack  = var.nodes_per_rack
}
```

Currently, if we try to `terraform apply` a change in this block, we are disallowed. However, this seems like a very useful and common change that should be enabled from Terraform.

Otherwise, how are we supposed to ensure our Terraform definition of the cluster is in-line with the real cluster?

### New or Affected Resource(s)

* instaclustr_cluster

**Comment by peter-toms** [comment]
thanks for the suggestion @ProfMoo ill raise it with the team and get back to you

**Comment by peter-toms** [comment]
adding internal reference for this work: INS-11384

**Comment by peter-toms** [comment]
Hi @ProfMoo, appreciate your patience on this one, I'm following up in order to ensure we have the correct prioritisation and understanding of the work.  

By allowing an alteration of the rack_allocation block this would imply that a user is able to dynamically add or remove nodes from an existing cluster.  Do I have the correct concept here?  Would you be able to elaborate further on your use-case for me?

Thanks in advance.

**Comment by ProfMoo** [comment]
Hi @peter-toms. It's been a while since I was working on this Terraform, but I'll try to remember the intent here.

The user story is:
"As the customer-side maintainer of the Instaclustr Kafka clusters, I want to be able to adjust the cluster node count up and down so that I can control the full lifecycle of the Kafka cluster entirely from Terraform"

After working with Instaclustr for a while, it seems to me that a lot of the cluster sizing operations need to be done manually by Instaclustr employees. So perhaps this ask is tough to pull off. But I think it's extremely desirable. The entirely Terraform-driven workflow is the standard across many cloud providers, so it's a big workflow change to send out e-mails and tickets to accomplish tasks.

**Comment by peter-toms** [comment]
thanks @ProfMoo for the clarification and cheers for framing like a user story, that helps build a common understanding!

Some good news, that this is a feature planned for delivery in the coming year.  As you mentioned above it currently requires support interaction (this is mainly due to the complexity of the operations involved).  We plan to also release changes to the Terraform provider as part of the work.  Will keep you updated on our progress, thanks again for your patience.

**Comment by arjunrajnetapp** [comment]
Support for adding nodes for Kafka is now available through the Instaclustr Terraform Provider v2 from all versions starting from v2.0.0 - https://registry.terraform.io/providers/instaclustr/instaclustr/latest/docs/resources/kafka_cluster_v2

Accordingly we will be closing this issue, thank you for raising it.
