### ISSUE TITLE
Publish to Terraform provider registry

### ISSUE THREAD

**Issue by peter-toms** [instaclustr/terraform-provider-instaclustr#7]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Publish this repo to the Terraform modules repository https://www.terraform.io/docs/registry/modules/publish.html

### New or Affected Resource(s)

None

**Comment by janlud** [comment]
Hi, we are using instaclustr Kafka resources. I would like to ask about ETA of publishing the module into terraform registry. We have the provider now locally and because of Terraform limitations we are not able to use TF 0.13 features (count, for_each, depends_on) on the instaclustr module.
Terraform requires to have the provider configuration inside the module because otherwise it assumes it's located in the registry.terraform.io registry. Because of the provider config in the module we cannot use the above mention features. More details here for example here: https://github.com/hashicorp/terraform/issues/25172#issuecomment-641348089

**Comment by peter-toms** [comment]
Hi @janlud our plan to have the Terraform provider published by the end of this week (AEST), thanks.

**Comment by peter-toms** [comment]
apologies for the delays in getting this one out, am working with our internal teams to move this along, thanks

**Comment by peter-toms** [comment]
adding internal reference for this work: INS-7488

**Comment by iamhail** [comment]
The provider has been published to the registry.
See blog: https://www.instaclustr.com/instaclustr-terraform-provider-added-to-terraform-provider-registry/#
